# Python and algorithms

##### Сomplete this part of test without using any libs (your code must not contain keyword 'import')

#### 1. Implement function str_to_dict(some_str) which returnes dictionary, where keys are string characters, and values are their quantity in the string:

<div style="text-align: right">1 point</div>

In [ ]:
def str_to_dict(some_str):  
    """
    :param some_str: str
    :return: dict
    """
    # YOUR CODE HERE
    result_dict = {}
    for c in some_str:
      if c in result_dict.keys():
        result_dict[c] += 1
      else: result_dict[c] = 1

    return result_dict

In [ ]:
print('Str to dict:', str_to_dict('dataroot_university'))

Str to dict: {'d': 1, 'a': 2, 't': 3, 'r': 2, 'o': 2, '_': 1, 'u': 1, 'n': 1, 'i': 2, 'v': 1, 'e': 1, 's': 1, 'y': 1}

Expected Output: 
<table>
  <tr>
    <td>Str to dict:</td>
    <td> {'d': 1, 'a': 2, 't': 3, 'r': 2, 'o': 2, '_': 1, 'u': 1, 'n': 1, 'i': 2, 'v': 1, 'e': 1, 's': 1, 'y': 1} </td> 
  </tr>

#### 2. Implement function sec_smallest(numbers) which returns second smallest item in the list, without using the built-in sorting methods (your code mustn't contain such words as 'sort', 'sorted'):

<div style="text-align: right">1 point

In [ ]:
def sec_smallest(numbers):
    """
    :param numbers: list[int]
    :return: int    
    """
    # YOUR CODE HERE
    first = numbers[0]
    second = numbers[0]

    for number in numbers:
      if number < first:
        second = first
        first = number
      elif number < second and not number == first:
        second = number
    
    return second

In [ ]:
print('Sec_smallest:', sec_smallest([1, 2, -8, -8, -2, 0]))

Sec_smallest: -2

Expected Output: 
<table>
  <tr>
    <td>Sec_smallest:</td>
    <td> -2 </td> 
  </tr>

#### 3. Implement function prime_nums(n) that returns list of numbers which  are simple and < n:





<div style="text-align: right">1 point</div>

In [96]:
def is_prime(number):
  for i in range(2, round(number**(1/2))+1):
    if number % i == 0:
      return False
  return True

def prime_nums(n):
    """
    :param n: int
    :return: list[int]
    """
    # YOUR CODE HERE
    result = [];
    for i in range(2, n+1):
      if is_prime(i):
        result.append(i)
    return result

In [97]:
print('Prime numbers:', prime_nums(30))

Prime numbers: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

Expected Output:
<table>
  <tr>
    <td>Prime numbers:</td>
    <td>[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]</td>
  </tr>

#### 4. Implement function max_sum_index(tuples), which returnes index of tuple in the list with maximum sum of elements:

<div style="text-align: right">1 point</div>

In [ ]:
def max_sum_index(tuples):  
    '''
    :param tuples: list[tuple]
    :return: int
    '''
    # YOUR CODE HERE
    max_sum = sum(tuples[0])
    result_index = 0

    for (index, item) in enumerate(tuples):
      current_sum = sum(item)
      if current_sum > max_sum:
        max_sum = current_sum
        result_index = index
    return result_index

In [ ]:
print('Index: ', max_sum_index([(10, 20), (40, 32), (30, 25)]))

Index:  1

Expected Output: 
<table>
  <tr>
    <td>Index:</td>
    <td> 1 </td> 
  </tr>

**5. Implement function gcd(x, y), which returns the greatest common divisor of n and m.**
<div style="text-align: right">1 point</div>

In [ ]:
def gcd(x, y):   
    '''
    :params m,n: int
    :return: int
    '''
    # YOUR CODE HERE
    if x == 0 or y == 0: return x + y
    if x > y: return gcd(x % y, y)
    else: return gcd(x, y % x)

In [ ]:
print("GCD: ", gcd(160, 180))

GCD:  20

Expected Output: 
<table>
  <tr>
    <td>GCD:</td>
    <td> 20 </td> 
  </tr>

#### 6. Implement recursive sum of the list:
<div style="text-align: right">1 point</div>

In [ ]:
def recursive_list_sum(data_list):
    """
    :param data_list: list[list]
    """
    # YOUR CODE HERE
    result = 0
    for i in data_list:
      if isinstance(i, list):
        result += recursive_list_sum(i)
      else:
        result += i
    return result

In [ ]:
print('The sum of a list is ', recursive_list_sum([1, 2, [3, 4], [5, 6], [7, 8, 9, [10]]]))

The sum of a list is  55

Expected Output:
<table>
  <tr>
    <td>The sum of a list is 55</td> 
  </tr>

#### 7. Implement decorator which returns function signature and it's return value:
<div style="text-align: right">1 point</div>

In [ ]:
def debug(func):
    """
    :param func: function
    """
    # YOUR CODE HERE
    def wrapper(*args):
      result = func.__name__ + '{}'.format(args)
      result += ' was called and returned {}'.format(func(*args))
      return result
    return wrapper

In [ ]:
@debug
def add(a, b):
    return a + b

add(3, 4)

'add(3, 4) was called and returned 7'

Expected Output:
<table>
  <tr>
    <td>add(3, 4) was called and returned 7</td>
  </tr>

#### 8. Implement class Conv, that contains method to_roman(self, n), which converts decimal numbers to Roman numerals:

<div style="text-align: right">2 points</div>

In [ ]:
class Conv:
    def __init__(self):
        self.val = [
            1000, 900, 500, 400,
            100, 90, 50, 40,
            10, 9, 5, 4, 1
        ]

        self.syb = [
            'M', 'CM', 'D', 'CD',
            'C', 'XC', 'L', 'XL',
            'X', 'IX', 'V', 'IV',
            'I'
        ]
        
    def to_roman(self, num):    
        """
        :param self:
        :param n: int
        :return: str    
        """
        # YOUR CODE HERE
        current_index = 0;
        result = '';
        while num > 0:
          if num >= self.val[current_index]:
            result += self.syb[current_index]
            num -= self.val[current_index]
          else: current_index += 1
        return result

In [ ]:
print('Converted:', Conv().to_roman(44))

Converted: XLIV

Expected Output:
<table>
  <tr>
    <td>Converted:</td>
    <td>XLIV</td> 
  </tr>

#### 9. Implement class CombinationsList, that contains method get_combinations(self, my_list), which returns all combinations of elements of given list, including empty element and in order, law of which can be discrovered from the expected output:
<div style="text-align: right">3 points</div>

In [ ]:
class CombinationsList:
    @staticmethod
    def my_combinations(iterable, r):
      pool = list(iterable)
      n = len(pool)
      if r > n:
          return
      indices = list(range(r))
      yield list(pool[i] for i in indices)
      while True:
          for i in reversed(range(r)):
              if indices[i] != i + n - r:
                  break
          else:
              return
          indices[i] += 1
          for j in range(i+1, r):
              indices[j] = indices[j-1] + 1
          yield list(pool[i] for i in indices)  


    @staticmethod
    def get_combinations(my_list):
        """
        :param self:
        :param my_list: list
        :return: list[list]
        """
        # YOUR CODE HERE
        result = []
        for i in range(len(my_list)+1):
          combination = CombinationsList.my_combinations(my_list, i)
          result += combination
        return result

In [ ]:
print('Combinations:', CombinationsList().get_combinations([1, 'a', 2]))

Combinations: [[], [1], ['a'], [2], [1, 'a'], [1, 2], ['a', 2], [1, 'a', 2]]
Combinations: [[], [1], [2], [3], [4], [1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4], [1, 2, 3], [1, 2, 4], [1, 3, 4], [2, 3, 4], [1, 2, 3, 4]]

Expected Output:
<table>
  <tr>
    <td>Combinations:</td>
    <td>[[], [1], ['a'], [2], [1, 'a'], [1, 2], ['a', 2], [1, 'a', 2]]</td> 
  </tr>

#### 10. Create base class <code>Rocket</code> and it's subclass <code>Shuttle</code>. The parent class contains methods <code>getMission()</code>, <code>addMission()</code> and <code>getName()</code>. The subclass <code>Shuttle</code> contains method <code>getDescription()</code>. Notice that we have not defined <code>getName()</code>, <code>getMission()</code>, <code>addMission()</code> in the <code>Shuttle</code> class but we are still able to access them, because the class <code>Shuttle</code> inherits them from the <code>Rocket</code> class. Use <code>super()</code> method to have ability to call those methods of the base class.
<div style="text-align: right">3 points</div>

In [ ]:
class Rocket:

    def __init__(self, name, mission):
        """
        :param name: str
        :param mission: str or list
        """
        # attributes are private to class Rocket
        self.__name = name      
        self.__mission = mission

    def getMission(self): 
        """
        : return str or list
        """
        return self.__mission

    def addMission(self, mission): 
        # procedure method which adds a new mission. There can be one (str) or multiple (list) existing missions
        """
        : param mission: str
        """
        # YOUR CODE HERE
        if not type(self.__mission) == list:
          self.__mission = [self.__mission]

        self.__mission.append(mission)


    def getName(self):
        """
        : return str
        """
        # YOUR CODE HERE
        return self.__name

    
class Shuttle(Rocket):

    def __init__(self, name, mission, model):
        # call parent constructor to set name and mission  
        """
        :param name: str
        :param mission: str or list
        : param model: str
        """
        # YOUR CODE HERE
        super().__init__(name, mission)
        self.__model = model

    def getDescription(self):
        return 'Name: {0}\nModel: {1}\nMissions: {2}'.format(self.getName(), self.__model, str(self.getMission()))

In [ ]:
dragon = Shuttle("Crew Dragon", "Dragon 2 pad abort test", "V2")
print(dragon.getDescription(), '\n')
dragon.addMission('Dragon 2 in-flight abort test')
print(dragon.getDescription())

Name: Crew Dragon
Model: V2
Missions: Dragon 2 pad abort test

Name: Crew Dragon
Model: V2
Missions: ['Dragon 2 pad abort test', 'Dragon 2 in-flight abort test']

Expected Output: 

                Name: Crew Dragon
                Model: V2
                Missions: Dragon 2 pad abort test
                
                Name: Crew Dragon
                Model: V2
                Missions: ['Dragon 2 pad abort test', 'Dragon 2 in-flight abort test']